version: "3.3"
services:

  redis:
    image: "redis:latest"
    container_name: "faqueue-redis"
    command: ["redis-server","--port 8586", "--appendonly", "yes"]
    ports:
      - "8586:8586"
    volumes:
      - ./docker/redis/data:/data

networks:
  default:
    external:
      name: "faqueue"